export const qualitativeFaults = [
  {
    component: 'Układ hamulcowy',
    part: 'Sworzeń pedału/dźwigni ręcznej hamulca roboczego',
    description: 'Zbyt ciasne pasowanie sworznia',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Sworzeń pedału/dźwigni ręcznej hamulca roboczego',
    description: 'Nadmierne zużycie lub zbyt duży luz sworznia',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Stan pedału hamulcowego/dźwigni ręcznej hamulca i skok elementu uruchamiającego hamulce',
    description: 'Nadmierny lub zbyt mały skok jałowy',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Stan pedału hamulcowego/dźwigni ręcznej hamulca i skok elementu uruchamiającego hamulce',
    description: 'Pedał hamulca nie zwalnia się (luzuje) prawidłowo.',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Stan pedału hamulcowego/dźwigni ręcznej hamulca i skok elementu uruchamiającego hamulce',
    description: 'Nadmierny opór',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Zawór sterujący hamulca postojowego',
    description: 'Luźne połączenia lub nieszczelność układu',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Zawory hamulcowe (nożne, luzujące, sterujące, bezpieczeństwa)',
    description: 'Zawór uszkodzony lub nadmierny wypływ powietrza',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Zawory hamulcowe (nożne, luzujące, sterujące, bezpieczeństwa)',
    description: 'Ubytek lub wyciek płynu hamulcowego',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Zawory hamulcowe (nożne, luzujące, sterujące, bezpieczeństwa)',
    description: 'Niesprawny zawór bezpieczeństwa',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Sztywne przewody hamulcowe',
    description: 'Stan przewodów grozi awarią lub pęknięciem',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Sztywne przewody hamulcowe',
    description: 'Wycieki z przewodów lub ich połączeń',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Sztywne przewody hamulcowe',
    description: 'Przewody uszkodzone lub nadmiernie skorodowane',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Okładziny i klocki hamulcowe',
    description: 'Nadmierne zużycie klocków lub okładzin',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Okładziny i klocki hamulcowe',
    description: 'Brak okładziny lub klocka',
    dangerLevels: ['MAJOR'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Bębny hamulcowe, tarcze hamulcowe',
    description: 'Zanieczyszczenie bębna lub tarczy (olej, smar itp.)',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ hamulcowy',
    part: 'Bębny hamulcowe, tarcze hamulcowe',
    description: 'Brak bębna lub tarczy',
    dangerLevels: ['MAJOR'],
  },
  {
    component: 'Układ kierowniczy',
    part: 'Przekładnia kierownicza',
    description: 'Mechanizm obraca się ciężko lub z zacięciami',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ kierowniczy',
    part: 'Przekładnia kierownicza',
    description: 'Nadmierny luz na wale przekładni kierowniczej',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ kierowniczy',
    part: 'Wspomaganie układu kierowniczego',
    description: 'Wyciek płynu',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ kierowniczy',
    part: 'Wspomaganie układu kierowniczego',
    description: 'Mechanizm wspomagania nie działa',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Układ kierowniczy',
    part: 'Drążki kierownicze',
    description: 'Nadmierne luzy w połączeniach (przegubach)',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ kierowniczy',
    part: 'Drążki kierownicze',
    description: 'Pęknięcie lub deformacja jakiejkolwiek części',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Układ kierowniczy',
    part: 'Drążki kierownicze',
    description: 'Nieprawidłowy montaż drążków kierowniczych i końcówek drążków',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła drogowe i mijania',
    description: 'Uszkodzenie układu projektorowego (odbłyśnik i klosz)',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła drogowe i mijania',
    description: 'Brak lub niedziałanie świateł drogowych',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła drogowe i mijania',
    description: 'Brak lub niedziałanie świateł mijania',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Przednie, tylne i boczne światła pozycyjne, światła obrysowe',
    description: 'Uszkodzenie klosza',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Przednie, tylne i boczne światła pozycyjne, światła obrysowe',
    description: 'Uszkodzenie źródła światła',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła stopu',
    description: 'Barwa inna niż czerwona',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła stopu',
    description: 'Uszkodzenie źródła światła',
    dangerLevels: ['MINOR', 'SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Światła',
    part: 'Światła kierunkowskazu i światła awaryjne',
    description: 'Uszkodzenie źródła światła',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła kierunkowskazu i światła awaryjne',
    description: 'Nie działają w jednej fazie',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła kierunkowskazu i światła awaryjne',
    description: 'Przełącznik nie działa lub nie działa prawidłowo',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła cofania',
    description: 'Włączanie na biegu innym niż wsteczny',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Światła',
    part: 'Światła cofania',
    description: 'Oślepiają innych użytkowników drogi',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Amortyzatory',
    description: 'Niepewne mocowanie amortyzatorów do podwozia lub osi',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Amortyzatory',
    description: 'Amortyzator jest uszkodzony i wykazuje duże wycieki lub uszkodzenie',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Sworznie wahaczy',
    description: 'Nadmierne zużycie sworznia lub łożysk sworznia, lub sworzni wahaczy',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Sworznie wahaczy',
    description: 'Brak lub znaczące uszkodzenie osłon gumowych',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Rury wydechowe i tłumiki',
    description: 'Nieszczelność lub niepewne mocowanie układu wydechowego',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Rury wydechowe i tłumiki',
    description: 'Spaliny przedostają się do wnętrza kabiny lub przedziału dla pasażerów',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Przeniesienie napędu',
    description: 'Nadmierne zużycie łożysk wału napędowego',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Przeniesienie napędu',
    description: 'Zły stan przegubów elastycznych',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Przeniesienie napędu',
    description: 'Uszkodzony, zgięty wał lub półoś',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Mocowanie silnika',
    description: 'Zawieszenia silnika zużyte, wyraźnie i znacząco uszkodzone, obluzowane lub pęknięte',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Mocowania nadwozia',
    description: 'Niepewne mocowania nadwozia lub kabiny',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Mocowania nadwozia',
    description: 'Wyraźne przesunięcie nadwozia/kabiny względem podwozia',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Mocowania nadwozia',
    description: 'Nadmierna korozja punktów mocowania nadwozia samonośnego',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Drzwi i zamki',
    description: 'Drzwi źle się otwierają lub zamykają',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Drzwi i zamki',
    description: 'Brakujące, obluzowane lub zniszczone: drzwi, zawiasy, zamki, słupki drzwi, klamki',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Siedzenie kierowcy',
    description: 'Nieprawidłowe działanie elementów regulacji i ustawienia siedzenia.',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Siedzenie kierowcy',
    description: 'Mocowanie siedzeń w miejscach nieprzewidzianych do tego konstrukcyjnie dla danego typu pojazdu',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Błotniki, fartuchy przeciwbłotne',
    description: 'Brak, obluzowanie lub znaczące skorodowanie części',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Nadwozie i osprzęt',
    part: 'Błotniki, fartuchy przeciwbłotne',
    description: 'Niewłaściwe położenie względem koła jezdnego',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Instalacja elektryczna',
    part: 'Akumulator(y)',
    description: 'Niepewne mocowanie',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },

  {
    component: 'Instalacja elektryczna',
    part: 'Akumulator(y)',
    description: 'Wyciek, pęknięcie obudowy',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },

  {
    component: 'Instalacja elektryczna',
    part: 'Złącza i przewody elektryczne',
    description: 'Niepewne mocowanie lub niewłaściwe zabezpieczenie instalacji elektrycznej',
    dangerLevels: ['MINOR', 'SIGNIFICANT', 'MAJOR'],
  },

  {
    component: 'Instalacja elektryczna',
    part: 'Złącza i przewody elektryczne',
    description: 'Instalacja w złym stanie',
    dangerLevels: ['MINOR', 'SIGNIFICANT', 'MAJOR'],
  },

  {
    component: 'Instalacja elektryczna',
    part: 'Złącza i przewody elektryczne',
    description: 'Uszkodzona lub zużyta izolacja',
    dangerLevels: ['MINOR', 'SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Ogumienie',
    part: 'Koła',
    description: 'Znaczące odkształcenie lub zużycie koła',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Ogumienie',
    part: 'Koła',
    description: 'Niewłaściwe zamocowanie pierścieni ustalających',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Ogumienie',
    part: 'Opony',
    description: 'Różne rozmiary opon na tej samej osi lub na kołach bliźniaczych',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Ogumienie',
    part: 'Opony',
    description: 'Opona obciera o inne elementy nadwozia pojazdu',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Ogumienie',
    part: 'Opony',
    description: 'Układ kontroli ciśnienia w ogumieniu jest uszkodzony lub wyraźnie nie działa',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Ogumienie',
    part: 'Opony',
    description: 'Opony o widocznych pęknięciach obnażających lub naruszających ich osnowę albo odkształcone',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Pasy i zapięcia',
    description: 'Uszkodzenie pasów bezpieczeństwa',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Pasy i zapięcia',
    description: 'Uszkodzenie lub nieprawidłowe działanie klamry pasa bezpieczeństwa',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Pasy i zapięcia',
    description: 'Brak miejsc kotwiczenia pasów',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Napinacze pasów bezpieczeństwa',
    description: 'Brak napinacza lub napinacz niezgodny z typem pojazdu',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Systemy poduszki powietrznej SRS',
    description: 'Wskaźnik autodiagnostyki układu SRS wskazuje dowolny rodzaj awarii w układzie',
    dangerLevels: ['SIGNIFICANT'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Zamki i urządzenia przeciwwłamaniowe',
    description: 'Urządzenie uniemożliwiające uruchomienie pojazdu nie działa',
    dangerLevels: ['MINOR'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Sygnał dźwiękowy',
    description: 'Niepewne działanie przycisku sygnału',
    dangerLevels: ['MINOR'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Sygnał dźwiękowy',
    description: 'Nie działa',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Prędkościomierz',
    description: 'Prędkościomierz umieszczony poza polem widzenia kierowcy',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Dodatkowe wyposażenie pojazdu',
    part: 'Prędkościomierz',
    description: 'Brak podświetlenia',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Zagadnienia związane z ochroną środowiska',
    part: 'Urządzenia kontrolne emisji spalin',
    description: 'Brak zamontowanego urządzenia kontrolnego emisji spalin, przeróbka urządzenia lub wyraźnie nieprawidłowe działanie',
    dangerLevels: ['MINOR', 'SIGNIFICANT'],
  },
  {
    component: 'Zagadnienia związane z ochroną środowiska',
    part: 'Wycieki płynów',
    description: 'Nadmierny wyciek dowolnego płynu, który może zagrażać środowisku lub bezpieczeństwu innych użytkowników drogi',
    dangerLevels: ['SIGNIFICANT', 'MAJOR'],
  },
]

export const quantitativeFaults = [
  {
    component: 'Układ hamulcowy',
    part: 'Hamulec roboczy',
    description: 'Maksymalna różnica hamulca roboczego',
    minValue: 0,
    maxValue: 30,
    unit: '%',
  },
  {
    component: 'Układ hamulcowy',
    part: 'Hamulec postojowy',
    description: 'Maksymalna różnica hamulca postojowego',
    minValue: 0,
    maxValue: 30,
    unit: '%',
  },
  {
    component: 'Układ hamulcowy',
    part: 'Hamulec roboczy',
    description: 'Skuteczność hamulca roboczego',
    minValue: 58,
    maxValue: 100,
    unit: '%',
  },
  {
    component: 'Układ hamulcowy',
    part: 'Hamulec postojowy',
    description: 'Skuteczność hamulca postojowego',
    minValue: 29,
    maxValue: 100,
    unit: '%',
  },
  {
    component: 'Układ kierowniczy',
    part: 'Koło',
    description: 'Zbieżność - przednia oś',
    minValue: -6,
    maxValue: 6,
    unit: 'mm/m',
  },
  {
    component: 'Układ kierowniczy',
    part: 'Koło',
    description: 'Zbieżność - tylna oś',
    minValue: -6,
    maxValue: 6,
    unit: 'mm/m',
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Zawieszenie',
    description: 'Przednia oś',
    minValue: 0,
    maxValue: 15,
    unit: '%',
  },
  {
    component: 'Podwozie, zawieszenie i inne',
    part: 'Zawieszenie',
    description: 'Tylna oś',
    minValue: 0,
    maxValue: 15,
    unit: '%',
  },
]

export const engineTypes = ['Diesel', 'Benzyna', 'Elektryczny', 'Hybryda']
export const bodyTypes = ['SUV', 'Coupe', 'Limuzyna', 'Sedan']
export const cars = [
  {
    make: 'Audi',
    models: ['A4', 'A6', 'A8']
  },
  {
    make: 'Mercedes-Benz',
    models: ['GLA', 'GLC']
  },
]
