version: "3.6"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
  server:
    build: server
    container_name: server
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - postgres
    volumes:
      - ./server/src:/server/src
      - ./server/prisma:/server/prisma
    env_file:
      - .env
  client:
    build: client
    container_name: client
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8080:8080"
    depends_on:
      - server
    volumes:
      - ./client/src:/client/src:cached
    env_file:
      - .env
